on:
  push:
    branches: [main]
  workflow_call: {}
  workflow_dispatch: {}

name: Build

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            nodejs_arch: x64
            nodejs_version: "^18.20.5"
            nodejs_version_major: 18
            platform: linux-x64
          - os: ubuntu-22.04
            container: node:18-alpine3.17
            nodejs_version_major: 18
            platform: linuxmusl-x64
          - os: ubuntu-22.04-arm
            nodejs_arch: arm64
            nodejs_version: "^18.20.5"
            nodejs_version_major: 18
            platform: linux-arm64
          - os: macos-13
            nodejs_arch: x64
            nodejs_version: "^18.20.5"
            nodejs_version_major: 18
            platform: darwin-x64
          - os: macos-14
            nodejs_arch: arm64
            nodejs_version: "^18.20.5"
            nodejs_version_major: 18
            platform: darwin-arm64
          - os: windows-2019
            nodejs_arch: x64
            nodejs_version: "^18.20.5"
            nodejs_version_major: 18
            platform: win32-x64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Dependencies (Linux musl)
        if: contains(matrix.container, 'alpine')
        run: apk add build-base git python3 --update-cache
      - name: Dependencies (Python)
        if: "!contains(matrix.container, 'alpine')"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Dependencies (Node.js)
        if: "!contains(matrix.container, 'alpine')"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version }}
          architecture: ${{ matrix.nodejs_arch }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install
        run: |
          corepack enable yarn
          yarn install
      - name: Prebuild
        run: yarn run-prebuildify

      - id: upload
        name: Upload prebuild
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: prebuilds/
          if-no-files-found: "error"
          retention-days: 1
          compression-level: 0
