on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Test

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "yarn"
      - run: yarn install
      - run: yarn compile
      - run: yarn test
